package com.likesmm.instahype.welcome;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.Fragment;

import com.likesmm.instahype.R;


public class PolicyFragment extends Fragment {
    int id;

    String user = "User Agreement\n" +
            "[Last revised: 10 January 2020]\n" +
            "\n" +
            "References in this Agreement to \"InstaHype\", \"we\", \"our\" or \"us\", are to like-smm.ru, and references to \"you\" or \"your\" are to the person with whom InstaHype enters into this Agreement. By accessing, using or signing up to use any of the services made available by InstaHype or one of its affiliates through the website (like-smm.ru), or any of our associated websites, APIs, or mobile applications (collectively the \"InstaHype\"), you agree that you have read, understood, and accept all of the terms and conditions contained in this Agreement, as well as our Privacy Policy. We reserve the right to modify or change the terms and conditions contained in this Agreement at any time and at its sole discretion. We will provide notice of these changes by updating the revised Agreement on the webpage (https://like-smm.ru/legal/) and changing the “[Last revised: ]” date on this page. Any and all modifications or changes to this Agreement will be effective immediately upon being announced on the website or released to users. As such, your continued use of InstaHype acts as acceptance of the amended agreement and rules. If you do not agree to any modification to this Agreement, you must stop using the InstaHype. We encourage you to frequently review the Agreement to ensure you understand the terms and conditions that apply to your access to, and use of, the InstaHype.\n" +
            "\n" +
            "1. Terms and Definitions Used in this Agreement\n" +
            "Customer means a site user who orders the services provided by the Contractor;\n" +
            "Contractor means a person (group of persons) providing services to the Customer;\n" +
            "Content - for the purposes of this Agreement, content shall be understood to mean the content posted on an Internet resource (in a social network or social service) in the form of a file (picture, video, music, audio, graphic image, etc.) that can be displayed electronically using computing machines (computers) and/or mobile devices that allow the reproduction of said content. For the purposes of this Agreement, content also includes the Customer's Account created in any social network / social service, including the content posted on it in whole or in part;\n" +
            "Spin-up (Promotion) means artificial promotion of the content posted by the Customer on a third-party Internet resource (in a social network or social service) by reaching the content viewing figures specified by the contract between the Contractor and the Customer on any service and/or artificial creation of the interest of users of any resource in the Customer’s content posted on said resource in order to attract and/or increase the number of users / gain new subscribers, ratings, likes, users, etc. For the purposes of this Agreement, the term “Promotion” is used in the same sense;\n" +
            "Payment Aggregator means a special service, which allows the Customer to make payments by bank cards or using electronic payment systems;\n" +
            "Applicable Law means the legislation of the state and its constituent entities (districts, states, colonies, etc.), to be applied to evaluate the actions of the Parties to the Agreement, resolve disputes and interpret the terms and conditions of this Agreement. In the Russian Federation, the applicable law is the legislation of the Russian Federation and its constituent entities;\n" +
            "Site, Service or Internet Resource means a collection of electronic documents in the form of an electronic program for the Internet network, which contains the information offered to users that has a single owner and manager, as well as can be found under a specific address on the Internet; Terms not specified and/or not listed in the text of this Agreement shall be interpreted in accordance with applicable law and/or the commonly used meaning and interpretation of a given term on the Internet.\n" +
            "\n" +
            "2. Scope of Agreement\n" +
            "2.1. The Contractor agrees to provide services to the Customer in promoting (spinning up) the Customer’s content (advertising services) in social networks and/or social user services in order to promote/attract and/or increase the number of users / gain new subscribers, user ratings, likes, classes, etc. The exact scope of services, as well as the type of resources and/or social services on (in) which the Customer’s content should be promoted, shall be determined by the Customer at its sole discretion, but only on the basis of the options for the provision of services proposed by the Contractor. The choice of the scope of specific services and payment for said services means the conclusion of this Agreement and entails the obligations of the parties to fulfill the Agreement;\n" +
            "2.2. The Contractor's services are provided in accordance with the terms and conditions of this Agreement, as well as the general Rules for the Provision of Services, which are an integral part of this Agreement;\n" +
            "2.3. The Contractor shall not provide services to promote the Customer's erotic, obscene or pornographic content, as well as advertising content aimed at encouraging Internet users to purchase / consume / use / store / engage in illicit trafficking in narcotic and/or psychotropic substances, weapons, alcoholic beverages, tobacco products, services of magicians, sorcerers, fortunetellers, gambling, affiliate programs, as well as other things (means, products, drugs, goods) whose circulation is limited or prohibited by applicable law;\n" +
            "2.4 The Contractor may refuse to promote the Customer's content if the Contractor believes that said content may violate the rights of others or is doubtful, i.e. created for making profit by illegal means;\n" +
            "2.5. The Contractor shall provide services strictly in accordance with this Agreement. The stages of rendering services are technological processes. At the stage of rendering services, it is not allowed to change their method, scope and/or payment method.\n" +
            "\n" +
            "3. Rights and Obligations of the Parties\n" +
            "3.1. The Contractor may provide (render) services to the Customer both in person and with the involvement of third parties without obtaining additional consent of the Customer in this regard;\n" +
            "3.2. The Customer agrees to pay for the services rendered by the Contractor in the amount, manner and terms stipulated by Section 4 of this Agreement;\n" +
            "3.3. When ordering the promotion of content, the Customer is obliged to ensure the availability of content at the online link indicated by them throughout the validity period of this Agreement. The Contractor shall not be liable provided that the resource on which the content is posted is not operational, as well as for the absence and/or blocking and/or removal of the Customer’s content by third parties or by the Customer themselves.\n" +
            "3.4. The Customer may not remove content during the provision of the services without the consent of the Contractor throughout the validity period of the Agreement;\n" +
            "3.5. If the Customer's failure to comply with the provisions of para. 3.3., 3.4. of the Agreement results in the impossibility of the Contractor to provide the services and the Customer has failed to notify the Contractor of the occurrence of said circumstances, the Contractor's obligations under this Agreement shall be deemed to be fulfilled, and the funds paid by the Customer for the provision of the services shall be deemed to be non-refundable;\n" +
            "3.6. The Customer is obliged to accept the new terms and conditions of the offer, which become effective 14 (fourteen) calendar days after publication on the site https://like-smm.ru;\n" +
            "3.7. The Customer may not use the services of other services for promotion in social media throughout the validity period of the Agreement;\n" +
            "3.8. If the Customer's content is deleted (blocked) by the Customer and/or third parties, and subsequently restored, the Contractor has the right to unilaterally suspend the provision of services and/or extend the period of their provision for a period of time necessary to eliminate the adverse effects caused by said circumstances or refuse to further provide services to the Customer (fulfillment of the Agreement) without returning to the Customer the funds paid by the Customer;\n" +
            "3.9. The Parties agree that the official response (statement) of the technical support of the Internet resource (service) email: admin@like-smm.ru, on which the Customer’s content is posted, unofficial messages of the support staff of the Internet resource (service), messages in the media, as well as analytical data of the Contractor's employees shall be deemed to be reliable confirmation of the Customer's failure to comply with the provisions of para. 3.3., 3.4. of the Agreement;\n" +
            "3.10. The Contractor also has the right to unilaterally extend the time for the provision of the services subject to occurrence of the following circumstances:\n" +
            "- technical problems of the resource (service), on which the Customer's content is posted;\n" +
            "- introduction of filters and updates in the social network and/or social service that impede the promotion of content;\n" +
            "- modification of algorithms of the social network and/or social service that impede the promotion of content.\n" +
            "3.11. The Parties have agreed that the official response (statement) of the technical support of the Internet resource (service), on which the Customer’s content is posted, unofficial messages of the support staff of the Internet resource (service), messages in the media, as well as analytical data of the Contractor's employees shall be deemed to be reliable confirmation of the onset of circumstances referred to in para. 3.10. of the Agreement;\n" +
            "3.12. The Contractor agrees not to take any actions during and after the provision of the services that may adversely affect the Customer's business reputation.\n" +
            "\n" +
            "4. Cost, Payment Procedure and Period of Services\n" +
            "4.1. By purchasing any paid service on the site, you agree that the money spent cannot be returned.\n" +
            "4.2. The types and cost of the Contractor's services are available on the Contractor's website in the “services” section;\n" +
            "4.3. Payment for the services provided by the Contractor in accordance with this Agreement shall be made before the actual provision of the services. The Contractor shall proceed with the provision of the services if the Customer makes a full advance payment, i.e. full amount for the provision of the services, to the account of the Contractor;\n" +
            "4.4. Payment under this Agreement shall be made by the Customer through payment methods available on the Contractor's website. The Parties have agreed that the moment of the beginning of fulfillment of the Customer's obligation to pay for the services is the moment of acceptance of the terms and conditions of this Agreement. The moment of the beginning of fulfillment of the Contractor's obligations as well as the moment of entry into force of this Agreement is the moment the funds are credited to the Contractor's account. The Contractor proceeds with the provision of the services to the Customer within 24 hours from the moment the funds are credited to the Contractor's bank account. To make a payment, the Customer must provide the necessary information. In the case of payment through payment systems (payment aggregators) from bank cards and/or other bank accounts, the Customer shall make sure that they have the right to dispose of the funds in said accounts. The Customer is also obligated to exclude third-party access to information that allows third parties to use the Customer's accounts to pay for and order the Contractor's services (bank card numbers, bank name, PIN codes, cvv2 and cvc2 codes, etc.). The risk of unauthorized payment of the Contractor's services from the Customer's accounts shall lie entirely with the Customer. The Customer shall be solely liable for unauthorized payment from their accounts of the services rendered by the Contractor made by third parties. Payment for the services from the Customer's account(s) shall be recognized by the Customer as authorized and made by the Customer themselves in any and all cases.\n" +
            "\n" +
            "5. Liability of the Parties\n" +
            "5.1. The Parties shall be held liable for non-fulfillment or improper fulfillment of their obligations hereunder in accordance with the current legislation of the Russian Federation.\n" +
            "5.2. The Customer uses the granted rights to use the Service at their own risk.\n" +
            "5.3. The Customer agrees that no software is error free.\n" +
            "5.4. The Customer agrees that in order to handle the Service, the Contractor must use software (web browsers, operating systems, etc.) and hardware (personal computers, network equipment, etc.) produced and provided by third parties, and the Contractor cannot be held liable for the quality their performance.\n" +
            "5.5. The Contractor assumes no liability for possible unsubscribing, blocking and other sanctions imposed by social media after using the Service, the Customer assumes full liability in this regard.\n" +
            "\n" +
            "6. Force Majeure\n" +
            "6.1. The Parties shall be exempted from liability for non-fulfillment or improper fulfillment of their obligations hereunder if said improper fulfillment was impossible due to force majeure circumstances. The Parties have agreed to consider force majeure circumstances as external and extraordinary events that were absent at the time of signing this Agreement and occurred contrary to the will and desire of the Parties, the effect of which the Parties could not have foreseen and could not have prevented with measures and means that could be justifiably and reasonably expected from a bona fide acting Party. Such circumstances include inter alia warfare and military operations, epidemics, fires, natural disasters, acts and actions of government bodies that make it impossible for the Parties to fulfill their obligations under this Agreement and recognized as force majeure circumstances;\n" +
            "6.2. A Party reporting the presence of force majeure circumstances shall notify the other party in writing of their occurrence and the expected duration no later than 5 (five) business days from the moment of their occurrence. If the reporting Party fails to send a notice within the specified period, it shall be deprived of the right to invoke such circumstances in the future;\n" +
            "6.3. The time period for the fulfillment of obligations under this Agreement shall be extended for the period of impossibility of their fulfillment due to force majeure circumstances.\n" +
            "\n" +
            "7. Changes to the terms of the User Agreement\n" +
            "7.1. This User Agreement may be changed by the Rightholder unilaterally. Notification of the User of the changes to the terms of the User Agreement is published on the web page: https://like-smm.ru/legal/. Said changes to the terms of the User Agreement shall enter into force as from the date of their publication, unless otherwise specified in the corresponding publication.\n" +
            "\n" +
            "8. Validity of the Agreement\n" +
            "8.1. This Agreement shall enter into force upon acceptance of its terms and conditions and crediting of funds in payment for the services provided by the Contractor to the Contractor's bank account and shall remain valid until the Parties fulfill their obligations in full;\n" +
            "8.2. The Customer has the right to early terminate the Agreement prior to its expiry by notifying the Contractor to that effect at least 30 (thirty) calendar days in advance. In case of early termination of the Agreement at the initiative of the Customer, the payment received by the Contractor for the provision of the services is not refundable even if the Contractor failed to fulfill all their obligations assumed by them hereunder;\n" +
            "8.3. In the event of termination of this Agreement for any other reason, the Parties are obliged to fulfill all their obligations that have arisen up to that point;\n" +
            "\n" +
            "9. Confidentiality\n" +
            "9.1. The Parties undertake to maintain confidentiality of the information they received from each other or which became known to them in the course of fulfilling their obligations under this Agreement, as well as knowledge, experience, know-how and other information about which it is expressly agreed that it is confidential. The Parties undertake not to make publicly available or disclose in general or in particular said information to any third party without the prior written consent of the other Party under this Agreement;\n" +
            "9.2. The requirements of para. 8.1. hereof shall not apply to cases of disclosure of confidential information at the request of authorized bodies where provided for by law.\n" +
            "\n" +
            "10. Customer's Personal Data\n" +
            "10.1. The Customer gives their consent to the Contractor to the processing of personal data provided at the conclusion of the Agreement, including:\n" +
            "10.1.1. last name, given name, patronymic name;\n" +
            "10.1.2. e-mail address;\n" +
            "10.1.3. country and city of residence;\n" +
            "10.2. The Contractor is entitled to transfer the Customer's personal data to third parties if said transfer is necessary for the Contractor to fulfill their obligations to the Customer hereunder.\n" +
            "10.3. Personal data processing means recording, systematization, accumulation, storage, clarification (updating, changing), extraction, usage, transfer (distribution, provision, accessing), including cross-border, depersonalization, blocking, deletion, destruction of personal data that are not subject to special categories, the processing of which requires the written consent of the Customer.\n" +
            "10.4. Personal data processing is carried out in order to fulfill the Contractor's obligations under the Agreement, provide the Customer with technical support, consider applications and claims of the Customers, send informational messages to the Customer's email address, as well as to confirm the fact of registration on the Site and to cause other actions to be performed on the Site by a certain individual.\n" +
            "10.5. The Customer may withdraw their consent to the processing of personal data, as well as delete or change their personal data at any time by sending a notice to the Contractor from the Customer's email address specified during registration on the Site to the Contractor's email address: admin@like-smm.ru. However, the Customer understands that the Contractor has the right to continue using such information to the extent permitted by applicable law.\n" +
            "10.6. Technical information shall be understood to mean information that is automatically transferred to the Contractor in the process of using the Site using the software installed on the Customer's hardware. Technical information shall not be deemed to be personal data. The Contractor shall use cookies and similar technologies that allow identification of the Customer's hardware. Cookies are text files available to the Service for processing information on the activity of the Customer's hardware. The Customer may disable cookies in the browser settings.\n" +
            "10.7. The Contractor may provide information about the Customer to law enforcement bodies or other state bodies as part of judicial proceedings or as part of an investigation on the basis of a court decision, a compulsory request or in the manner of cooperation, as well as in other cases provided for by applicable law.\n" +
            "10.8. The Contractor may provide information about the Customer to third parties for the identification and suppression of fraudulent activities, as well as for the elimination of technical or security problems.\n" +
            "11. Other Terms and Conditions\n" +
            "\n" +
            "\n" +
            "11.1. The Parties have agreed that all notifications provided for by this Agreement (with the exception of claims) may be carried out by the Parties by e-mail. The Contractor's email address is the address specified in the “Contact Us” section or another relevant section of the Contractor's site (email: admin@like-smm.ru). The Customer's email address is the address specified by the Customer on the Contractor's site when ordering services. Letters and other documents received from the Customer from other e-mail addresses will not be accepted and will not be considered by the Contractor;\n" +
            "11.2. In case of a change in name, location, bank details and other data, each of the Parties shall notify the other Party in writing of said changes within 5 (five) days;\n" +
            "11.3. In all other respects not specified by this Agreement, the Parties shall be governed by applicable law.\n" +
            "\n" +
            "email: admin@like-smm.ru";

    String policy = "PRIVACY POLICY\n" +
            "like-smm.ru (\"InstaHype\") (“we”, “us” and “our”) respect and protect the privacy of visitors to our websites and our customers who use our services. To ensure transparency, this Privacy Policy describes our information handling practices when you access content we own or operate on the websites located at like-smm.ru or any other websites, pages, features, or content we own or operate (collectively, the \"Site(s)\") and/or when you use the InstaHype mobile app, any InstaHype API or third party applications relying on such an API, and related services (referred to collectively hereinafter as \"Services\"). Please take a moment to read this Privacy Policy carefully. If you have any questions about this Privacy Notice, please contact us at admin@like-smm.ru.\n" +
            "\n" +
            "ACCEPTANCE OF PRIVACY POLICY\n" +
            "By accessing and using our Services, you signify acceptance to the terms of this Privacy Policy. Where we require your consent to process your personal information, we will ask for your consent to the collection, use, and disclosure of your personal information as described further below. InstaHype may provide additional \"just-in-time\" disclosures or additional information about the data collection, use and sharing practices of specific Services. These notices may supplement or clarify InstaHype’s privacy practices or may provide you with additional choices about how InstaHype processes your data. If you do not agree with or you are not comfortable with any aspect of this Privacy Policy, you should immediately discontinue access or use of our Services.\n" +
            "\n" +
            "CHANGES TO THIS PRIVACY POLICY\n" +
            "We reserve the right to modify this Privacy Policy at any time, and when required by law, we will notify you of changes to this Privacy Policy. If we make any material changes we will notify you by email (sent to the e-mail address specified in your account) or by means of a notice on our Services prior to the change becoming effective.\n" +
            "\n" +
            "THE PERSONAL INFORMATION WE COLLECT\n" +
            "Personal information is data that can be used to identify you directly or indirectly, or to contact you. Our Privacy Policy covers all personal information that you voluntarily submit to us and that we obtain from our partners. This Privacy Policy does not apply to anonymised data, as it cannot be used to identify you. You may be asked to provide personal information anytime you are in contact with any InstaHype companies. The InstaHype companies may share your personal information with each other and use it consistent with this Privacy Policy. They may also combine it with other information to provide and improve our products, services, and content (see the section below). Except as described in this Privacy Policy, InstaHype will not give, sell, rent or loan any personal Information to any third party.\n" +
            "\n" +
            "PERSONAL INFORMATION COLLECTED\n" +
            "We collect personal information to provide you with our Services. When we require certain personal information from users it is because we are required by law to collect this information or it is relevant for specified purposes. Any information you provide to us that is not required is voluntary. You are free to choose whether to provide us with the types of personal information requested, but we may not be able to serve you as effectively or offer you all of our Services when you do choose not to share certain information with us. For example, we collect personal information which is required under the law to open an account, add a payment method, or execute a transaction. We also collect personal information when you use or request information about our Services, subscribe to marketing communications, request support, complete surveys, or sign up for a InstaHype event. We may also collect personal information from you offline, such as when you attend one of our events, or when you contact customer support. We may use this information in combination with other information we collect about you as set forth in this Policy. We collect the following types of information:\n" +
            "• Personal Identification Information: Full name, date of birth, age, nationality, gender, signature, utility bills, photographs, phone number, home address, and/or email.\n" +
            "• Formal Identification Information: Tax ID number, passport number, driver’s license details, national identity card details, photograph identification cards, and/or visa information.\n" +
            "• Financial Information: Bank account information, payment card primary account number (PAN), transaction history, trading data, and/or tax identification.\n" +
            "• Transaction Information: Information about the transactions you make on our Services, such as the name of the recipient, your name, the amount, and/or timestamp.\n" +
            "• Employment Information: Office location, job title, and/or description of role.\n" +
            "• Online Identifiers: Geo location/tracking details, browser fingerprint, OS, browser name and version, and/or personal IP addresses.\n" +
            "• Usage Data: Survey responses, information provided to our support team, public social networking posts, authentication data, security questions, user ID, click-stream data and other data collected via cookies and similar technologies. Please read our Cookie Policy for more information.\n" +
            "\n" +
            "HOW YOUR PERSONAL INFORMATION IS USED\n" +
            "Our primary purpose in collecting personal information is to provide you with a secure, smooth, efficient, and customised experience. In general, we use personal information to create, develop, operate, deliver, and improve our Services, content and advertising, and for loss prevention and anti-fraud purposes. We may use this information in the following ways:\n" +
            "• To maintain legal and regulatory compliance\n" +
            "• Some of our core Services are subject to laws and regulations requiring us to collect and use your personal identification information, formal identification information, financial information, transaction information, employment information, online identifiers, and/or usage data in certain ways. For example, InstaHype must identify and verify customers using our Services in order to comply with anti-money laundering and terrorist financing laws across jurisdictions. In addition, we use third parties to verify your identity by comparing the personal information you provided against third-party databases and public records. We also may use photo and video recording to verify the user while using our service. When you seek permissions to raise Digital Currency buy and sell limits associated with your InstaHype Account, we may require you to provide additional information which we may use in collaboration with service providers acting on our behalf to verify your identity or address, and/or to manage risk as required under applicable law. The consequences of not processing your personal information for such purposes is the termination of your account as we cannot perform the Services in accordance with legal and regulatory requirements.\n" +
            "• EEA Residents: For individuals who reside in the European Economic Area (including the United Kingdom) or Switzerland (collectively “EEA Residents”), pursuant to Article 6 of the EU General Data Protection Regulation (GDPR) or any equivalent legislation (collectively “EEA Data Protection Law”), we process this personal information to comply with our legal obligations.\n" +
            "• To enforce our terms in our user agreement and other agreements\n" +
            "• InstaHype Handles very sensitive information, such as your identification and financial data, so it is very important for us and our customers that we are actively monitoring, investigating, preventing and mitigating any potentially prohibited or illegal activities, enforcing our agreements with third parties, and/or violations of our posted user agreement or agreement for other Services. In addition, we may need to collect fees based on your use of our Services. We collect information about your account usage and closely monitor your interactions with our Services. We may use any of your personal information collected on our Services for these purposes. The consequences of not processing your personal information for such purposes is the termination of your account as we cannot perform our Services in accordance with our terms.\n" +
            "• To provide InstaHype’s Services\n" +
            "• We process your personal information in order to provide the Services to you. For example, when you want to buy Digital Currency, we require certain information such as your identification, contact information, and payment information. We cannot provide you with Services without such information.\n" +
            "• To provide Service communications\n" +
            "• We send administrative or account-related information to you to keep you updated about our Services, inform you of relevant security issues or updates, or provide other transaction- related information. Without such communications, you may not be aware of important developments relating to your account that may affect how you can use our Services.\n" +
            "• To provide customer service\n" +
            "• We process your personal information when you contact us to resolve any questions, disputes, collect fees, or to troubleshoot problems. We may process your information in response to another customer’s request, as relevant. Without processing your personal information for such purposes, we cannot respond to your requests and ensure your uninterrupted use of the Services.\n" +
            "• To ensure quality control\n" +
            "• We process your personal information for quality control and staff training to make sure we continue to provide you with accurate information. If we do not process personal information for quality control purposes, you may experience issues on the Services such as inaccurate transaction records or other interruptions. Our basis for such processing is based on the necessity of performing our contractual obligations with you.\n" +
            "• EEA Residents: For all of the above categories, excluding the first bullet point, pursuant to EEA Data Protection Law, we process this personal information based on our contract with you.\n" +
            "• To ensure network and information security\n" +
            "• We process your personal information in order to enhance security, monitor and verify identity or service access, combat spam or other malware or security risks and to comply with applicable security laws and regulations. The threat landscape on the internet is constantly evolving, which makes it more important than ever that we have accurate and up- to-date information about your use of our Services. Without processing your personal information, we may not be able to ensure the security of our Services. EEA Residents: Pursuant to EEA Data Protection Law, we process this personal information to satisfy our legal obligations.\n" +
            "• For research and development purposes\n" +
            "• We process your personal information to better understand the way you use and interact with InstaHype’s Services. In addition, we use such information to customise, measure, and improve InstaHype’s Services and the content and layout of our website and applications, and to develop new services. Without such processing, we cannot ensure your continued enjoyment of our Services. Our basis for such processing is based on legitimate interest.\n" +
            "• EEA Residents: Pursuant to EEA Data Protection Law, we process this personal information to satisfy our legitimate interests as described above.\n" +
            "• To enhance your website experience\n" +
            "• We process your personal information to provide a personalised experience, and implement the preferences you request. For example, you may choose to provide us with access to certain personal information stored by third parties Without such processing, we may not be able to ensure your continued enjoyment of part or all of our Services.\n" +
            "• EEA Residents: Pursuant to EEA Data Protection Law, we process this personal information to satisfy our legitimate interests as described above.\n" +
            "• To facilitate corporate acquisitions, mergers, or transactions\n" +
            "• We may process any information regarding your account and use of our Services as is necessary in the context of corporate acquisitions, mergers, or other corporate transactions. You have the option of closing your account if you do not wish to have your personal information processed for such purposes.\n" +
            "• EEA Residents: Pursuant to EEA Data Protection Law, we process this personal information to satisfy our legitimate interests as described above.\n" +
            "• To engage in marketing activities\n" +
            "• Based on your communication preferences, we may send you marketing communications to inform you about our events or our partner events; to deliver targeted marketing; and to provide you with promotional offers based on your communication preferences. We use information about your usage of our Services and your contact information to provide marketing communications. You can opt-out of our marketing communications at any time.\n" +
            "• EEA Residents: Pursuant to EEA Data Protection Law, we process this personal information to satisfy on your consent. We will not use your personal information for purposes other than those purposes we have disclosed to you, without your permission. From time to time we may request your permission to allow us to share your personal information with third parties. You may opt out of having your personal information shared with third parties, or allowing us to use your personal information for any purpose that is incompatible with the purposes for which we originally collected it or subsequently obtained your authorisation. If you choose to so limit the use of your personal information, certain features or InstaHype may not be available to you.\n" +
            "\n" +
            "INFORMATION FROM THIRD PARTY SOURCES\n" +
            "From time to time, we may obtain information about you from third party sources as required or permitted by applicable law, such as public databases, credit bureaus, ID verification partners, resellers and channel partners, joint marketing partners, and social media platforms.\n" +
            "• Public Databases, Credit Bureaus & ID Verification Partners: We obtain information about you from public databases and ID verification partners for purposes of verifying your identity. ID verification partners use a combination of government records and publicly available information about you to verify your identity. Such information includes your name, address, job role, public employment profile, credit history, status on any sanctions lists maintained by public authorities, and other relevant data. We obtain such information to comply with our legal obligations, such as anti-money laundering laws. Pursuant to EEA Data Protection Law, our lawful basis for processing such data is compliance with legal obligations. In some cases, we may process additional data about you to ensure our Services are not used fraudulently or for other illicit activities. In such instances, processing is necessary for us to continue to perform our contract with you and others. COLLECTION & USE OF INFORMA TION COLLECTED AUTOMATICALLY We receive and store certain types of information automatically, such as whenever you interact with the Sites or use the Services. This information does not necessarily reveal your identity directly but may include information about the specific device you are using, such as the hardware model, device ID, operating system version, web-browser software (such as Firefox, Safari, or Internet Explorer) and your Internet Protocol (IP) address/MAC address/device identifier. For example, we automatically receive and record information on our server logs from your browser, including how you came to and used the Services; your IP address; device type and unique device identification numbers, device event information (such as crashes, system activity and hardware settings, browser type, browser language, the date and time of your request and referral URL), broad geographic location (e.g. country or city-level location) and other technical data collected through cookies, pixel tags and other similar technologies that uniquely identify your browser. We may also collect information about how your device has interacted with our website, including pages accessed and links clicked. We may use identifiers to recognise you when you arrive at the Site via an external link, such as a link appearing on a third party site. Please refer to the InstaHype Cookie Policy for more information about our use of cookies.\n" +
            "\n" +
            "WHY WE SHARE PERSONAL INFORMATION WITH OTHER PARTIES\n" +
            "We take care to allow your personal information to be accessed only by those who really need to in order to perform their tasks and duties, and to share with third parties who have a legitimate purpose for accessing it. InstaHype will never sell or rent your personal information. We will only share your information in the following circumstances:\n" +
            "• We share your information with third party identity verification services in order to prevent fraud. This allows InstaHype to confirm your identity by comparing the information you provide us to public records and other third party databases. These service providers may create derivative data based on your personal information that can be used solely in connection with provision of identity verification and fraud prevention services.\n" +
            "• We may share your information with service providers under contract who help with parts of our business operations such as bill collection, marketing, and technology services. Our contracts require these service providers to only use your information in connection with the services they perform for us, and prohibit them from selling your information to anyone else.\n" +
            "• We share your information with financial institutions with which we partner to process payments you have authorised.\n" +
            "• We may share your information with companies or other entities that we plan to merge with or be acquired by. Should such a combination occur, we will require that the new combined entity follow this Privacy Policy with respect to your personal information. You will receive prior notice of any change in applicable policies.\n" +
            "• We may share your information with companies or other entities that purchase InstaHype assets pursuant to a court-approved sale under U.S. bankruptcy law and / or where we are required to share your information pursuant to insolvency law in the U.K. or in any other jurisdiction;\n" +
            "• We may share your information with law enforcement, officials, or other third parties when we are compelled to do so by a subpoena, court order, or similar legal procedure, or when we believe in good faith that the disclosure of personal information is necessary to prevent physical harm or financial loss, to report suspected illegal activity or to investigate violations of our User Agreement or any other applicable policies.\n" +
            "• If you establish a InstaHype Account indirectly on a third party website or via a third party application, any information that you enter on that website or application (and not directly on a InstaHype website will be shared with the owner of the third party website or application and your information will be subject to their privacy policies.\n" +
            "\n" +
            "HOW PERSONAL INFORMATION IS SHARED WITH THIRD-PARTY SITES AND SERVICES\n" +
            "If you use your InstaHype Account to transfer Digital Currency in connection with the purchase or sale of goods or services, we or you may also provide the seller with your shipping address, name, and/or email to help complete your transaction with the seller. The seller is not allowed to use this information to market their services to you unless you have agreed to it. If an attempt to transfer Digital Currency to your seller fails or is later invalidated, we may also provide your seller with details of the unsuccessful transfer. To facilitate dispute resolutions, we may provide a buyer with the seller's address so that goods can be returned to the seller. In connection with a Digital Currency transfer between you and a third party, including merchants, a third party may share information about you with us, such as your email address or mobile phone number which may be used to inform you that a transfer has been sent to or received from the third party. We may use this information in connection with such transfers to confirm that you are a InstaHype customer, that Digital Currency transfers are enabled, and/or to notify you that you have received Digital Currency. If you request that we validate your status as a InstaHype customer with a third party, we will do so. You may also choose to send Digital Currency to or request Digital Currency from an email address. In such cases, your user name will be displayed in an email message notifying the user of the designated email address of your action. Please note that merchants you interact with may have their own privacy policies, and InstaHype is not responsible for their operations, including, but not limited to, their information practices. Information collected by third parties, which may include such things as contact details or location data, is governed by their privacy practices. We encourage you to learn about the privacy practices of those third parties. If you authorise one or more third-party applications to access your InstaHype Account, then information you have provided to InstaHype may be shared with those third parties. Unless you provide further authorisation, these third parties are not allowed to use this information for any purpose other than to facilitate your transactions using InstaHype Services.\n" +
            "\n" +
            "HOW WE PROTECT AND STORE PERSONAL INFORMATION\n" +
            "We understand how important your privacy is, which is why InstaHype maintains (and requires its service providers to maintain) appropriate physical, technical and administrative safeguards to protect the security and confidentiality of the personal information you entrust to us. We may store and process all or part of your personal and transactional information, including certain payment information, such as your encrypted bank account and/or routing numbers, in the United States and elsewhere in the world where our facilities or our service providers are located. We protect your personal information by maintaining physical, electronic, and procedural safeguards in compliance with the applicable laws and regulations. For example, we use computer safeguards such as firewalls and data encryption, we enforce physical access controls to our buildings and files, and we authorise access to personal information only for those employees who require it to fulfill their job responsibilities. Full credit card data is securely transferred and hosted off-site by a payment vendor in compliance with Payment Card Industry Data Security Standards (PCI DSS). This information is not accessible to InstaHype staff. However, we cannot guarantee that loss, misuse, unauthorised acquisition, or alteration of your data will not occur. Please recognise that you play a vital role in protecting your own personal information. When registering with our Services, it is important to choose a password of sufficient length and complexity, to not reveal this password to any third-parties, and to immediately notify us if you become aware of any unauthorised access to or use of your account. Furthermore, we cannot ensure or warrant the security or confidentiality of information you transmit to us or receive from us by Internet or wireless connection, including email, phone, or SMS, since we have no way of protecting that information once it leaves and until it reaches us. If you have reason to believe that your data is no longer secure, please contact us at the email address, mailing address or telephone number listed at the end of this Privacy Policy.\n" +
            "\n" +
            "SPECIFIC CONSENT BY USERS IN SINGAPORE\n" +
            "If you are located in, or a resident of, Singapore, you specifically and voluntarily consent to the transfer of your personal information to our related entity and service providers in the EU, for the specific purposes of performing identity verification or checking, to enable us to prevent fraud and comply with our legal obligations. We require our service provider to treat your personal information in strict confidence and use appropriate security measures to protect it. We also require them to uphold all of our other obligations under this Privacy Policy. You may revoke your consent to this section at any time by emailing admin@like-smm.ru with the subject line “Revoke Singapore data consent”.\n" +
            "\n" +
            "HOW YOU CAN ACCESS OR CHANGE YOUR PERSONAL INFORMATION\n" +
            "You are entitled to review, correct, or amend your personal information, or to delete that information where it is inaccurate. You may do this at any time by logging in to your account and clicking the Profile or My Account tab. If you close your InstaHype Account, we will mark your account in our database as \"Closed,\" but will keep your account information in our database for a period of time described above. This is necessary in order to deter fraud, by ensuring that persons who try to commit fraud will not be able to avoid detection simply by closing their account and opening a new account. However, if you close your account, your personal information will not be used by us for any further purposes, nor sold or shared with third parties, except as necessary to prevent fraud and assist law enforcement, as required by law, or in accordance with this Privacy Policy.\n" +
            "\n" +
            "RIGHTS IN RELATION TO THE USE OF YOUR PERSONAL INFORMATION\n" +
            "Rights of access, correction and deletion You have a right of access to the personal information that we hold about you under European data protection legislation, and to some related information. You can also require any inaccurate personal information to be corrected or deleted. Right to object You can object to our use of your personal information for direct marketing purposes at any time and you may have the right to object to our processing of some or all of your personal information (and require them to be deleted) in some other circumstances. If you wish to exercise any of these rights, please contact us as set out below.\n" +
            "\n" +
            "RETENTION OF PERSONAL INFORMATION\n" +
            "We store your personal information securely throughout the life of your InstaHype Account. We will only retain your personal information for as long as necessary to fulfil the purposes for which we collected it, including for the purposes of satisfying any legal, accounting, or reporting obligations or to resolve disputes. While retention requirements vary by jurisdiction, information about our typical retention periods for different aspects of your personal information are described below.\n" +
            "• Contact Information such as your name, email address and telephone number for marketing purposes is retained on an ongoing basis until you un-subscribe. Thereafter we will add your details to our suppression list indefinitely.\n" +
            "• Content that you post on our website such as support desk comments, photographs, videos, blog posts, and other content may be kept indefinitely after you close your account for audit and crime prevention purposes.\n" +
            "• Recording of our telephone calls with you may be kept for a period of up to six years.\n" +
            "• Information collected via technical means such as cookies, webpage counters and other analytics tools is kept for a period of up to one year from expiry of the cookie.\n" +
            "\n" +
            "CHILDREN'S PERSONAL INFORMATION\n" +
            "\n" +
            "• We do not knowingly request to collect personal information from any person under the age of 18. If a user submitting personal information is suspected of being younger than 18 years of age, InstaHype will require the user to close his or her account and will not allow the user to continue buying or selling digital currencies. We will also take steps to delete the information as soon as possible. Please notify us if you know of any individuals under the age of 18 using our Services so we can take action to prevent access to our Services.\n" +
            "• INTERNATIONAL TRANSFERS OF PERSONAL INFORMATION\n" +
            "• Our service providers may store, transfer, and otherwise process your personal information in countries outside of the country of your residence, including the United States, the Philippines, and possibly other countries. We use approved Model Contractual Clauses for the international transfer of personal information collected in the European Economic Area and Switzerland, or require that any third party located in the U.S. receiving your personal information is certified under the E.U.-U.S. and/or the Swiss-U.S. Privacy Shield Frameworks and require that the third party agree to at least the same level of privacy safeguards as required under applicable data protection laws.\n" +
            "• If you have a complaint about our privacy practices and our collection, use or disclosure of personal information please contact us at admin@like-smm.ru.\n" +
            "• EEA USERS & DATA\n" +
            "• If you are a resident of the EEA, like-smm.ru (\"InstaHype\") is joint controllers with respect to your personal information. As joint controllers, these entities determine the means and purposes of processing data in relation to e-wallet and cryptocurrency transactions.\n" +
            "• Legal bases for processing personal information\n" +
            "• Our legal bases for processing under EEA Data Protection Law are described above in the sections entitled “How Your Information Is Used” and “Information From Third Party Partners.” We may process your personal information if you consent to the processing, to satisfy our legal obligations, if it is necessary to carry out our obligations arising from any contracts we entered with you, or to take steps at your request prior to entering into a contract with you, or for our legitimate interests to protect our property, rights or safety of InstaHype, our customers or others.\n" +
            "\n" +
            "Direct Marketing\n" +
            "If you are a current customer residing in the EEA, we will only contact you by electronic means (email or SMS) with information about our Services that are similar to those which were the subject of a previous sale or negotiations of a sale to you. If you are a new customer and located in the EEA, we will contact you if you are located in the EU by electronic means for marketing purposes only if you have consented to such communication. If you do not want us to use your personal information in this way, or to pass your personal information on to third parties for marketing purposes, please contact us at admin@like-smm.ru. You may raise such objection with regard to initial or further processing for purposes of direct marketing, at any time and free of charge. Direct marketing includes any communications to you that are only based on advertising or promoting products and services\n" +
            "\n" +
            "Individual Rights\n" +
            "EEA Residents have the following rights, which can be exercised by contacting us at admin@like-smm.ru so that we may consider your request under applicable law. You can set your communication preferences and make individual rights requests relating to your personal information in the account settings. We encourage you to make any individual rights requests through the account settings because it ensures that you have been authenticated already. Otherwise, when we receive an individual rights request via email we may take steps to verify your identity before complying with the request to protect your privacy and security.\n" +
            "• Right to withdraw consent. You have the right to withdraw your consent to the processing of your personal information collected on the basis of your consent at any time. Your withdrawal will not affect the lawfulness of InstaHype’s processing based on consent before your withdrawal.\n" +
            "• Right of access to and rectification of your personal information. You have a right to request that we provide you a copy of your personal information held by us. This information will be provided without undue delay subject to some fee associated with gathering of the information (as permitted by law), unless such provision adversely affects the rights and freedoms of others. You may also request us to rectify or update any of your personal information held by InstaHype that is inaccurate. Your right to access and rectification shall only be limited where the burden or expense of providing access would be disproportionate to the risks to your privacy in the case in question, or where the rights of persons other than you would be violated.\n" +
            "• Right to erasure. You have the right to request erasure of your personal information that: (a) is no longer necessary in relation to the purposes for which it was collected or otherwise processed; (b) was collected in relation to processing that you previously consented, but later withdraw such consent; or (c) was collected in relation to processing activities to which you object, and there are no overriding legitimate grounds for our processing. If we have made your personal information public and are obliged to erase the personal information, we will, taking account of available technology and the cost of implementation, take reasonable steps, including technical measures, to inform other parties that are processing your personal information that you have requested the erasure of any links to, or copy or replication of your personal information. The above is subject to limitations by relevant data protection laws.\n" +
            "• Right to data portability. If we process your personal information based on a contract with you or based on your consent, or the processing is carried out by automated means, you may request to receive your personal information in a structured, commonly used and machine-readable format, and to have us transfer your personal information directly to another “controller”, where technically feasible, unless exercise of this right adversely affects the rights and freedoms of others. A “controller” is a natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of your personal information.\n" +
            "• Right to restriction of or processing. You have the right to restrict or object to us processing your personal information where one of the following applies:\n" +
            "• (a) You contest the accuracy of your personal information that we processed. In such instances, we will restrict processing during the period necessary for us to verify the accuracy of your personal information.\n" +
            "• (b) The processing is unlawful and you oppose the erasure of your personal information and request the restriction of its use instead.\n" +
            "• (c) We no longer need your personal information for the purposes of the processing, but it is required by you to establish, exercise or defense of legal claims.\n" +
            "• (d) You have objected to processing, pending the verification whether the legitimate grounds of InstaHype’s processing override your rights.\n" +
            "• Restricted personal information shall only be processed with your consent or for the establishment, exercise or defense of legal claims or for the protection of the rights of another natural or legal person or for reasons of important public interest. We will inform you if the restriction is lifted.\n" +
            "• Notification of erasure, rectification and restriction.We will communicate any rectification or erasure of your personal information or restriction of processing to each recipient to whom your personal information have been disclosed, unless this proves impossible or involves disproportionate effort. We will inform you about those recipients if you request this information.\n" +
            "• Right to object to processing. Where the processing of your personal information is based on consent, contract or legitimate interests you may restrict or object, at any time, to the processing of your personal information as permitted by applicable law. We can continue to process your personal information if it is necessary for the defense of legal claims, or for any other exceptions permitted by applicable law.\n" +
            "• Automated individual decision-making, including profiling. You have the right not to be subject to a decision based solely on automated processing of your personal information, including profiling, which produces legal or similarly significant effects on you, save for the exceptions applicable under relevant data protection laws.\n" +
            "• Right to lodge a complaint. If you believe that we have infringed your rights, we encourage you to contact us at admin@like-smm.ru so that we can try to resolve the issue.\n" +
            "• Storage of your personal information. InstaHype will try to limit the storage of your personal information to the extent that storage is necessary to serve the purpose(s) for which the personal information was processed, to resolve disputes, enforce our agreements, and as required or permitted by law.\n" +
            "• Data Protection Officer:You may reach the InstaHype Data Protection Officer at admin@like-smm.ru.\n" +
            "• Your rights to personal information are not absolute. Access may be denied when:\n" +
            "• Denial of access is required or authorized by law;\n" +
            "• Granting access would have a negative impact on other's privacy;\n" +
            "• Granting access would have a negative impact on other's privacy;\n" +
            "• To protect our rights and properties; and\n" +
            "• Where the request is frivolous or vexatious.\n" +
            "\n" +
            "HOW TO CONTACT US\n" +
            "• If you have questions or concerns regarding this Privacy Policy, or if you have a complaint, you should first contact us at like.hype.app@gmail.com.";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        PolicyFragmentArgs args = PolicyFragmentArgs.fromBundle(getArguments());
        id = args.getResId();
//        MainActivity.prefConfig.displayToast(""+args.getResId());
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_policy, container, false);
        TextView tvPolicy = view.findViewById(R.id.tvPolicy);
        if (id == 1) {
            ((AppCompatActivity) getActivity()).getSupportActionBar().setTitle("PRIVACY POLICY");
            tvPolicy.setText(policy);
        } else {
            ((AppCompatActivity) getActivity()).getSupportActionBar().setTitle("User Agreement");
            tvPolicy.setText(user);
        }
        return view;
    }

}